# -*- coding: utf-8 -*-
"""Template-Notebook-Stefan

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQ7GvYgH4vZCqbs-2o2LT5f8v0wy8_4D

# Proyek Analisis Data: Nama dataset
- Nama: Stefan Agustinus
- Email: s14agustinus@gmail.com
- Id Dicoding: stefan_agustinus

## Menentukan Pertanyaan Bisnis

- Produk apa saja yang memiliki jumlah permintaan tersedikit di e-commerce Brazil?
- Produk apa saha yang memiliki jumlah permintaan terbanyak di e-commerce Brazil?

## Menyaipkan semua library yang dibuthkan
"""



"""## Data Wrangling

### Gathering Data
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

product_df = pd.read_csv('/content/drive/MyDrive/Brazilian E-Commerce Public Data/products_dataset.csv', delimiter=",")
product_df.head()

order_item_df = pd.read_csv("/content/drive/MyDrive/Brazilian E-Commerce Public Data/order_items_dataset.csv", delimiter=",")
order_item_df.head()

"""### Assessing Data"""

product_df.info()

product_df.isna().sum()

print("Jumlah duplikasi: ", product_df.duplicated().sum())

product_df.describe()

order_item_df.info()

print("Jumlah duplikasi: ", order_item_df.duplicated().sum())

order_item_df.describe()

"""### Cleaning Data"""

product_df[product_df.product_category_name.isna()]

product_df.product_category_name.value_counts()

product_df.fillna(value= "cama_mesa_banho", inplace = True)

product_df.isna().sum()

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

product_df.describe(include = "all")

order_item_df.describe(include = "all")

new_join = pd.merge(
    left = product_df[["product_id","product_category_name"]],
    right = order_item_df[["product_id","order_id"]],
    how = "inner",
    left_on = "product_id",
    right_on = "product_id"
)

where1 = new_join.groupby(["product_category_name"])["order_id"].count().sort_values(ascending = True)\
                 .reset_index(name="total_orders")

where1.head(10)

where2 = new_join.groupby(["product_category_name"])["order_id"].count().sort_values(ascending = False)\
                 .reset_index(name="total_orders")

where2.head(10)

"""## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(40, 6))

colors = ["#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3"]

sns.barplot(x="total_orders", y="product_category_name", data=where2.head(5), palette=colors, ax=ax[0])
ax[0].set_ylabel(None)
ax[0].set_xlabel(None)
ax[0].set_title("Best Performing Product", loc="center", fontsize=15)
ax[0].tick_params(axis ='y', labelsize=12)

sns.barplot(x="total_orders", y="product_category_name", data=where1.sort_values(by="total_orders", ascending=True).head(5), palette=colors, ax=ax[1])
ax[1].set_ylabel(None)
ax[1].set_xlabel(None)
ax[1].yaxis.set_label_position("left")
ax[1].yaxis.tick_left()
ax[1].set_title("Worst Performing Product", loc="center", fontsize=15)
ax[1].tick_params(axis='y', labelsize=12)

"""### Pertanyaan 2:"""



"""## Conclusion

- Conclution pertanyaan 1
- conclution pertanyaan 2
"""

